import Link from 'next/link'
import { ArrowDownRight, ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Check, ChevronRight, Command, Layers3, MailOpen, Menu, MessageSquareText, NotebookPen, Sparkles, Workflow, X } from 'lucide-react'
import { products, workflowSteps, type Product } from '@/lib/products'
import { storeCategories } from '@/lib/categories'

export function Brand() { return <Link href="/" className="brand" aria-label="Flowmint AI home"><span className="brand-mark">f</span><span>Flowmint <b>AI</b></span></Link> }

export function Header() { return <header className="site-header"><div className="nav-wrap"><Brand/><nav className="desktop-nav" aria-label="Main navigation"><Link href="/products">Products</Link><Link href="/workflows">Workflows</Link><Link href="/about">About</Link><Link href="/resources">Resources</Link></nav><Link className="nav-cta" href="/products">Explore products <ArrowRight size={15}/></Link><details className="mobile-nav"><summary aria-label="Open menu"><Menu/><span className="sr-only">Menu</span></summary><nav><Link href="/products">Products</Link><Link href="/workflows">Workflows</Link><Link href="/about">About</Link><Link href="/resources">Resources</Link><Link href="/contact">Contact</Link></nav></details></div></header> }
export function Footer() { return <footer className="footer"><div className="footer-top"><div><Brand/><p>Practical digital products<br/>for modern work.</p></div><div className="footer-links"><div><span>EXPLORE</span><Link href="/products">Products</Link><Link href="/workflows">Workflows</Link><Link href="/resources">Resources</Link></div><div><span>FLOWMINT</span><Link href="/about">About</Link><Link href="/contact">Contact</Link></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Flowmint AI</span><span>Thoughtful tools for your everyday.</span></div></footer> }
export function Shell({children}:{children:React.ReactNode}) { return <><Header/><main id="main-content">{children}</main><Footer/></> }
export function Eyebrow({children}:{children:React.ReactNode}) { return <div className="eyebrow"><span className="eyebrow-dot"/>{children}</div> }
export function SectionHeading({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}) { return <div className="section-heading"><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{copy&&<p>{copy}</p>}</div> }
export function ProductCard({product}:{product:Product}) { const available=product.status==='available';return <article className={`product-card ${available?'featured-card':''}`}><div className="product-card-top"><span className="product-icon"><Workflow size={20}/></span><span className={`status ${available?'status-live':''}`}><i/>{available?'Available now':'In the works'}</span></div><p className="card-kicker">{product.category}</p><h3>{product.name}</h3><p className="card-description">{product.description}</p><Link href={product.href} className="card-link">{product.label}<ArrowUpRight size={16}/></Link></article> }
export function ProductGrid({limit}:{limit?:number}) { return <div className="product-grid">{products.slice(0,limit).map(p=><ProductCard key={p.slug} product={p}/>)}</div> }
const categoryIcons={ 'digital-planners':CalendarDays, journals:NotebookPen, ecards:MailOpen, 'ai-workflows':Workflow, 'prompt-library':MessageSquareText, ebooks:BookOpen }
export function ProductCategoryGrid(){return <div className="category-grid">{storeCategories.map(category=>{const Icon=categoryIcons[category.slug as keyof typeof categoryIcons];return <Link className="category-card" href={`/products/${category.slug}`} key={category.slug}><span className="category-icon"><Icon size={19}/></span><span className={`category-state ${category.status==='available'?'category-state-live':''}`}><i/>{category.status==='available'?'Explore':'Coming soon'}</span><h3>{category.name}</h3><p>{category.shortDescription}</p><span className="category-link">Explore category <ArrowUpRight size={14}/></span></Link>})}</div>}
export function WorkflowVisual() { return <div className="workflow-visual" aria-label="Workflow diagram: choose a category, scan the web, explore five topics, and shape a post"><div className="visual-topline"><span><span className="live-dot"/> YOUR WORKFLOW</span><span className="visual-control"><span/><span/><span/></span></div><div className="visual-title">From a category<br/>to <em>your next post.</em></div><div className="flow-list">{[{icon:'✳',title:'Choose a category',detail:'A subject you love to post about',kind:'input'},{icon:'⌕',title:'Scan the web',detail:'Find timely stories and ideas',kind:'process'},{icon:'✎',title:'Explore five topics',detail:'Review suggestions and sources',kind:'process'},{icon:'✓',title:'Shape your post',detail:'Your angle. Your voice. Your call.',kind:'output'}].map((item,i)=><div className={`flow-row ${item.kind}`} key={item.title}><span className="flow-icon">{item.icon}</span><span className="flow-text"><b>{item.title}</b><small>{item.detail}</small></span>{i<3&&<span className="flow-arrow"><ArrowDownRight size={14}/></span>}{i===3&&<span className="ready-tag"><Check size={12}/> READY</span>}</div>)}</div><div className="visual-foot"><span><Command size={13}/> Human judgment stays in the loop</span><span>WORKFLOW 001</span></div></div> }
export function ProductShelf() { return <div className="product-shelf" aria-label="Preview of Flowmint's LinkedIn content workflow and upcoming Idea Deck"><div className="shelf-top"><span><span className="live-dot"/> THE DIGITAL PRODUCT SHELF</span><span>FLOWMINT COLLECTION 01</span></div><div className="shelf-stage"><div className="shelf-product shelf-journal"><div className="journal-spine"/><span className="shelf-label">FREE WORKFLOW</span><span className="journal-star">✳</span><b>LinkedIn<br/>Content<br/>Workflow</b><small>SIX STEPS FROM IDEA TO POST</small></div><div className="shelf-product shelf-notion"><div className="notion-head"><span>↗</span><small>FLOWMINT GUIDE</small><span>•••</span></div><div className="notion-title">From idea<br/>to post.</div><div className="notion-task"><i/>Capture the idea</div><div className="notion-task"><i/>Find your angle</div><div className="notion-task"><i/>Review the draft</div><div className="notion-pill">PDF WORKFLOW</div></div><div className="shelf-product shelf-cards"><div className="card-back"><span>FLOWMINT<br/>IDEA DECK</span><b>✳</b><small>01 — FIND YOUR STARTING POINT</small></div><div className="card-front"><small>A PROMPT FOR TODAY</small><p>What would feel easier if you made it a little more repeatable?</p><span>FLOWMINT · 01</span></div></div><div className="shelf-spark shelf-spark-one">✳</div><div className="shelf-spark shelf-spark-two">✧</div></div><div className="shelf-bottom"><span>LinkedIn workflow <i/> Idea deck <i/> More digital tools ahead</span><span>MADE FOR MODERN WORK</span></div></div> }
export function CTA({title='Make room for the work that matters.',copy='Explore practical systems built to take repetition out of your day.',button='Explore products',href='/products'}:{title?:string;copy?:string;button?:string;href?:string}) { return <section className="cta-band"><div className="cta-orb"/><Eyebrow>START WITH A BETTER FLOW</Eyebrow><h2>{title}</h2><p>{copy}</p><Link className="button button-light" href={href}>{button}<ArrowRight size={16}/></Link></section> }
export function Newsletter() { return <section className="newsletter"><div><Eyebrow>THE FLOWMINT NOTE</Eyebrow><h2>A useful workflow,<br/>now and then.</h2><p>Practical ideas for making AI work feel a little more human and a lot more useful.</p></div><div className="signup-form"><label htmlFor="email">Get the occasional Flowmint note</label><div className="input-row"><input id="email" name="email" type="email" placeholder="you@example.com" autoComplete="email"/><button type="button" aria-label="Email signup integration not configured" disabled>Join the list <ArrowRight size={15}/></button></div><small>Email signup isn’t connected yet. Check back soon.</small></div></section> }
export function PageIntro({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}) { return <section className="page-intro"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p>{copy}</p></section> }
export { ArrowRight, ArrowUpRight, Check, ChevronRight, Layers3, Sparkles, Workflow, workflowSteps }
